### ISSUE TITLE
Ability to change the delimiter?

### ISSUE THREAD

**Issue by jackdh** [nbubna/store#103]
Hey,

I can't see it so excuse me if it is there, but could we add the ability to change the delimiter from the standard "."?

Thanks!

**Comment by nbubna** [comment]
Interesting. The delimiter for namespaces, you mean, right? What's the motive for changing that? It's the first i've heard of anyone wanting to.

**Comment by jackdh** [comment]
Yup for namespaces.

So I'm building a simple GUI for users to manage their local storage.

Some keys however have a period in which I can't control.


Based on the current API I can't see a way to loop through namespaces and their children namespaces recursively.

But I could loop through all keys however, check for the delimiter and split on that, I could build the heirarchy.

 So hopefully you can see the problem, if I could use a custom delimiter I could safely split on it.

Does that make sense or perhaps I'm missing something?

Thanks!






On 11 May 2022, at 19:21, Nathan Bubna ***@***.***> wrote:

﻿

Interesting. The delimiter for namespaces, you mean, right? What's the motive for changing that? It's the first i've heard of anyone wanting to.

**Comment by nbubna** [comment]
Makes sense. That said, there's no support for it right now, but it'd be a small change. I can add that.

**Comment by nbubna** [comment]
store._.delim = ':' // or whatever delim you want.

This changes the delim globally for all instances and storages as of version 2.14.0

**Comment by crutch12** [comment]
> store._.delim = ':' // or whatever delim you want.
> 
> This changes the delim globally for all instances and storages as of version 2.14.0

I think we should add it to `index.d.ts` declarations

**Comment by nbubna** [comment]
At this point, i have avoided adding any of the "developer tools" (store._) to the declarations.

Those are not public facing, so i maintain the right to change them with notice and not a major version. Somehow, adding them to the TS types feels like more of a promise to keep them stable.

Then again, they are and have been incredibly stable. So i would consider a PR to do that, if you want. I'm too busy to consider it right now. Just do it on a different issues, thx.

**Comment by crutch12** [comment]
Also, there is a mistake
```js
store._.delim= ':'
```
won't work

You should use
```js
store._.nsdelim = ':'
```

**Comment by nbubna** [comment]
Ah, yeah, i implemented it as nsdelim. It's all correct in the README.

**Comment by crutch12** [comment]
@nbubna here is PR for developer tools index.d.ts types: https://github.com/nbubna/store/pull/109

**Comment by crutch12** [comment]
I think it would be better if we could pass `delimiter` as argument for `store.namespace` function
Instead of overriding global variable. It may cause some problems if there are another packages which use `store2` too

**Comment by nbubna** [comment]
I think the concern would not be other packages using store2, but rather, 1) old data that used a different delim, and 2) other packages using store._.nsdelim.

But yeah, i think we can support both per-namespace and global.
