### ISSUE TITLE
Cache expires value always undefined

### ISSUE THREAD

**Issue by stefanKP50** [nbubna/store#106]
hi and thanks for store2.
trying to set cache expire value, min (ie. fourth parameter) value is always undefined when debug the _.set function in store.cache.js
I should not understood something but what ? Here is my code
`var ustorage = store.namespace(uniqId);
`
`ustorage.set('mykey', {firstdata:1, seconddata: 1}, 60);`

60 seconds not retrieved in cache !
Same if i do not use namespace.
Thanks

**Comment by nbubna** [comment]
Are you sure you have store.cache.js loaded in that window?
https://raw.githubusercontent.com/nbubna/store/master/src/store.cache.js

Cache won't work without the cache extension.

**Comment by stefanKP50** [comment]
@nbubna thanks for quick answer. Yes store.cache.js is loaded. When i console.log(area, key, string, min) in the _.set function in store.cache.js, result is ok for area, key, string but min is undefined.
After test, i found that the stringify function inside store2 (2.14.0) does not return the cache integer value but only the second parameter. I will test again for this stringify function.
Stefan

**Comment by stefanKP50** [comment]
Sure i do no not understand how works your stringify function, as for me, never return third parameter. So cache value is undefined and ignored. Perhaps miss understood the _replacer param? 
Thanks

**Comment by nbubna** [comment]
No, it's not you. There's a bug. When i added replacer support, i broke store.cache.js. I should only be passing "overwrite" to stringify as a replacer if it is a function, otherwise it needs to be passed on to _.set so extensions can use it. I'll try to fix this Thurs. Sorry, no time before then, i think.

**Comment by nbubna** [comment]
The 2.14.1 release is out, it fixes what was broken.
