### ISSUE TITLE
GPL-3 or MIT? 

### ISSUE THREAD

**Issue by phishalot** [nbubna/store#120]
Howdy, 

Since there is no GPL-3 license file (but there is a MIT one) in the repo would it make sense to remove the GPL-3 mention? 
https://github.com/nbubna/store/blob/b4f4c6f7c7883170c76512d1cc2704f6d01accdc/package.json#L32

**Comment by marcklingen** [comment]
+1, we screen for licenses of dependencies and `store2` popped up due to the potential GPL-3.0 license even though the project seems to be fully MIT

**Comment by marcklingen** [comment]
Just found your answers here:
- https://github.com/nbubna/store/issues/88#issuecomment-773536721
- https://github.com/nbubna/store/issues/121#issuecomment-1856154255

> In a lot of ways, specifying both GPL 3 and MIT seems contradictory, but the intent is to offer this under the "do whatever you want, as long as we're not liable" plan so you can use this in any stack, without legal considerations.

Is there a downside to using only "MIT" with your goal in mind? All other dependencies in our projects have only OSS licenses and I'd assume that including "OR GPL" will trigger copy-left alerts for many others as well.

**Comment by nbubna** [comment]
These are both OSS licenses, and if the *option* to use this under GPL 3 triggers an alert, then it's a false positive. You may use this under MIT or GPL. I offer both, choose whichever suits you.

**Comment by nbubna** [comment]
Ok. I give.
