### ISSUE TITLE
why did you added  "license": "(MIT OR GPL-3.0)"

### ISSUE THREAD

**Issue by opensrc0** [nbubna/store#121]
Hey,

Why did you added  "license": "(MIT OR GPL-3.0)", you can simply add  "license": "MIT". Is there something you are achieving by providing MIT or GPL-3.0 License ?

**Comment by nbubna** [comment]
I was following a precedent i'd seen done by other OSS, particularly in JS front-end. I wanted to ensure that this software was available for any and all use, whether in a GPL product or in a commercial business use.
