### ISSUE TITLE
Support AMD

### ISSUE THREAD

**Issue by mokkabonna** [nbubna/store#15]
If you are willing I could create a AMD integration as well.

**Comment by nbubna** [comment]
@mokkabonna Is this all resolved? If so, go ahead and close this issue. If not, what still needs to happen?

**Comment by tuoxiansp** [comment]
I met the same problem. When try to built it by r.js. 
Now I can only fix it by hack dist/store2.js:

    // ;(function(window, define) {
    define(function(require, exports, module) {

        ....some code

        //Expose store to the global object
        // window.store = store;

        module.exports = store;
    });

        // if (typeof define === 'function' && define.amd !== undefined) {
        //     define(function () {
        //         return store;
        //     });
        // } else if (typeof module !== 'undefined' && module.exports) {
        //     module.exports = store;
        // }

    // })(this, this.define);

**Comment by nbubna** [comment]
Blech. Universal module definitions are such a pain. Patches anyone? I don't use r.js and don't have time in my life to play around with it.

**Comment by sgratzl** [comment]
what about using https://github.com/umdjs/umd

**Comment by nbubna** [comment]
Does that work with r.js?

**Comment by robjens** [comment]
Please also demonstrate usage of the plugins. Test case is too simple.

**Comment by Jamesking56** [comment]
Any updates on this? I'm trying to use this module with Require.js and getting `Mismatched anonymous define() module`

**Comment by Jamesking56** [comment]
@nbubna I have a passing PR that fixes the issue #34 Please can you merge?
