### ISSUE TITLE
Fake Storage question

### ISSUE THREAD

**Issue by nozer** [nbubna/store#23]
I have 2 questions: 

1 - I think that if the browser does not support local storage, it falls back to a memory based storage? Can I prevent that from happening? (I may store large amount of info there and I do not want it to cause any slowness in browser. So, I would like to know if local or session storage is enabled on user's browser b4 attempting to save anything). 

2 - How do I know if localStorage or sessionStorage is supported? What would be equivalent to `store2.isLocalStorageSupported()` and `store2.isSessionStorageSupported()`? Are they `store.isFake()` and `store.session.isFake()`, respectively?

Thanks!

**Comment by nbubna** [comment]
Yeah, isFake() works for both ```store``` and ```store.session```. If ```isFake()``` returns true, you can assume that that storage (local or session) is unsupported for that browser (or browser mode).

As for preventing things from even being stored in local memory when using fake storage... that's a bit antithetical to the design, but i'm fairly sure you could monkey patch things to make that happen seamlessly. Let me think on the best way to do that for you...

**Comment by nozer** [comment]
I just did a test on safari (Version 8.0.6 (10600.6.3)) in private browsing mode and isFake() did not return false. Is that a bug? Because in private browsing mode, localStorage is not allowed.

**Comment by nozer** [comment]
Thanks for the offer above, I will see what I can do about memory storage.

**Comment by nbubna** [comment]
I think the following would do the trick. If the targeted storage area is fake (not supported), it just refuses to store anything.

```javascript
/**
 * Copyright (c) 2015 ESHA Research
 * Dual licensed under the MIT and GPL licenses:
 *   http://www.opensource.org/licenses/mit-license.php
 *   http://www.gnu.org/licenses/gpl.html
 *
 * Store nothing when storage is not supported.
 *
 * Status: ALPHA - due to being of doubtful propriety
 */
;(function(_) {

    var _set = _.set;
    _.set = function(area, key, string) {
        return area.isFake() ? undefined : _set.apply(this, arguments);
    };

})(window.store._);
```

**Comment by nozer** [comment]
Waow, thanks. But please do look at the isFake() returning false on private browsing mode in safari. It should return true.

**Comment by nbubna** [comment]
Reopening while i consider again the perpetual headache of Safari private mode...

**Comment by nozer** [comment]
LOL There is another store.js library ing Github and it was checking if storage is enabled by trying to write and then read from the localStorage. Maybe you guys can do something like that too to ensure.

**Comment by nbubna** [comment]
The problem with Safari private is that the storage API is provided but throws quota errors, which is exceedingly foolish. I could maybe forgive that if getItem were at least functional (i.e. you could save something in localStorage on non-private, then at least read it in private mode), but it's not. Useless. More fake than my in-memory fake storage.

Ok, enough kvetching. Back to thinking about solutions...

**Comment by nozer** [comment]
This is what that other library did

```
                var testKey = '__storejs__';
		store.set(testKey, testKey);
		if (store.get(testKey) != testKey) { store.disabled = true; }
		store.remove(testKey);

```

**Comment by nbubna** [comment]
Okay, version 2.3.0 is out and uses fake storage for Safari private mode. It also includes a store.onlyreal.js (which is a fixed version of the code i posted above). Thanks for being a squeaky wheel; i think this is a good move.

**Comment by nozer** [comment]
LOL. Thank you for the fix!
