### ISSUE TITLE
NuGet Update

### ISSUE THREAD

**Issue by djm61** [nbubna/store#24]
Is it possible to get the NuGet package updated to 2.3?  It's showing 2.1 right now.  Thanks!

**Comment by nbubna** [comment]
I forget about NuGet sometimes (i work on os x, after all).  I'll fire up a VM later and see if i can't figure out how to do that again. :)

**Comment by nbubna** [comment]
Ok, 2.3.0 is up on NuGet (being indexed at the moment). Also added grunt-nuget to make building and pushing packages easier.
