### ISSUE TITLE
Minified and SourceMap

### ISSUE THREAD

**Issue by michaelsogos** [nbubna/store#27]
Hi,

This library is great!
I'm using BOWER repository to download my front-end modules, and fortunately you already supply a minified version but not its SourceMap. Can you provide that too?

**Comment by nbubna** [comment]
Sounds reasonable...

**Comment by nbubna** [comment]
Ok, v2.3.2 has a source map. :)

**Comment by michaelsogos** [comment]
You are Great ;)

Thanks for your present.
