### ISSUE TITLE
app.js in /dist

### ISSUE THREAD

**Issue by yairEO** [nbubna/store#29]
what is this file for and why don't you explain anywhere its purpose?

**Comment by nbubna** [comment]
Build artifact for component.js users. I don't explain it, because if you need it, you already know what it is for. I don't personally advocate for componentjs, but i'm fine with supporting it in this way.

**Comment by yairEO** [comment]
I looked at the file and it wasn't clear to me what it's about..I don't even know what component.js is and i've been coding javascript for the past 12 years, and I know other people that for certain will get confused by that file, without a doubt. personally I use EE6 import/exports and I grab files from others githubs and modify them to be exported in the proper way, without require js and all those hacks.

**Comment by nbubna** [comment]
Component was one of the early client side package managers. I saw no reason to reject that PR. And it's still in use, so it's still supported. If you want to submit a PR to better support ES6 imports, i'd be happy to accept that too. With a library like this, i've no interest in being opinionated and/or exclusive about integration support.
