### ISSUE TITLE
Not supporting cross-tabs

### ISSUE THREAD

**Issue by drveresh** [nbubna/store#32]
Hi,

Currently it is only supporting same page/tab, but not working in multiple tabs for same pages/application. Now days, it is a basic use case that users would open same app on multiple tabs.

Please update me if this can be accommodated.

Thanks

**Comment by nbubna** [comment]
Well, it works that way already. It always has. It's kind of the whole point of localStorage, after all. Are you sure you're not getting some console errors? Or working in private mode?

**Comment by nbubna** [comment]
You might test and confirm that using localStorage directly works as you expect. If it doesn't, then neither will store2.

**Comment by drveresh** [comment]
By default the localStorage doesn't support syncing between more than one tab for same website/page/domain, and I was hoping your library will cover it.

**Comment by nbubna** [comment]
You are incorrect. I can open one of my apps in two tabs right now, set a value in localStorage in one tab and retrieve that value in the other tab.

**Comment by nbubna** [comment]
That is, unless, i'm in private mode.

**Comment by aMarCruz** [comment]
@nbubna you're right. It is so in my Chrome/Linux.
