### ISSUE TITLE
Example with addClass, removeClass and toggleClass

### ISSUE THREAD

**Issue by neuropass** [nbubna/store#33]
Would you be so kind provide some simple examples for saving a class and toggling a class please?
like some basic JQuey functions addClass, removeClass and toggleClass.

Or even better if there is pure JS example for those type of common usage?

**Comment by nbubna** [comment]
What on earth does that have to do with localStorage or sessionStorage? store2 is not for manipulating DOM elements.

**Comment by neuropass** [comment]
its for interfacing with localStorage is it not?
So Im asking if could show an  example on how to use store2 to save in local storage something like a class toggle etc. What am I missing? why such response like you just fell off the couch?  what was so appalling about my question?

**Comment by nbubna** [comment]
localStorage is for saving text, not DOM element states. They are so unrelated that an example won't teach anyone anything relevant to this library. It is not an issue with the store2 library. And i saw you cross-posted on marcuswestin's store library. This sort of thing belongs on stackoverflow, not here.

I can give you an example like where you do something like
```store('classFooOnElementBar', true)``` on some action, then look for that on page load like so ```$bar.toggleClass('foo', store('classFooOnElementBar'))```, but i don't use jQuery much lately and i don't see what the point of such a thing is.
