### ISSUE TITLE
Support for Mobile Devices?

### ISSUE THREAD

**Issue by GitHubDelphi** [nbubna/store#36]
I am looking for a disclaimer for the support of Mobile Devices.
Can you please point me to it?

Thanks.

**Comment by nbubna** [comment]
No disclaimers lying about. Just the license https://github.com/nbubna/store/blob/master/LICENSE-MIT

It will "work" in any browser. It's a wrapper for localStorage and sessionStorage that fakes it if it doesn't exist. Whether the device is mobile matters not.
