### ISSUE TITLE
nuget packet not updated

### ISSUE THREAD

**Issue by equisgroup** [nbubna/store#37]
Can anyone update nuget Install-Package store2 to lastest version? actually is 2.3.2.

**Comment by nbubna** [comment]
Ah, yeah, good ol' nuget, and me with my windows vms all in shambles. I'll try to squeeze it in today, but if not, it might take a few more days to get to it.

**Comment by nbubna** [comment]
It's up, or pending, at least. I don't have time to get windows up and test it right now.
