### ISSUE TITLE
Enhancement for store.get

### ISSUE THREAD

**Issue by marcelmeulemans** [nbubna/store#38]
Would you consider integrating a pull request that allows for `set`-ting the `alt` value of a `store.get` call in the case the requested key does not exist in the store? As far as I can tell this is currently not possible (in a single call). This enhancement would mean adding a an extra parameter `store.get(key[, alt][, write]);`.

**Comment by nbubna** [comment]
Yeah, i'd definitely at least consider it. Is there a particular use case or are you just hoping to save a few lines of code? Answering yes to the latter won't keep me from considering it, i'm just curious about the motivation.

**Comment by nbubna** [comment]
Still interested in making a PR for this? Does the new-ish ```transact``` function help alleviate need for this?

**Comment by nbubna** [comment]
Marcel, are you still interested in this?

**Comment by parkjoon** [comment]
Shouldn't that kind of logic be handled by the callee?

**Comment by onchie** [comment]
I think it's better to have a separate api for that, something like `store.getOrSet(key, alt)`.
You can create it yourself pretty simply via the plug-in system:
```javascript
_.fn('getOrSet', function(key, alt) {
    const value = this.get(key);
    if (value === undefined) {
        this.set(key, alt)
        return alt
    }
    return value;
});

// usage
const value = store.getOrSet(key, 'default value')
```

**Comment by nbubna** [comment]
I agree with evermediocre, this is probably best as a plugin.
