### ISSUE TITLE
It seems not support IE ?

### ISSUE THREAD

**Issue by 22996963** [nbubna/store#39]
Hi nbubna,
Thanks for your awesome store lib, Can It support IE8+?

I use the latest code, write a test, but it seems not work  on IE8,IE10.
It show the error as below:
"1.global failure (1, 0, 1)Rerun0 ms1.对象不支持此属性或方法Source:  http://localhost:63342/storeExample/js/store.array.js:43 
2.global failure (1, 0, 1)Rerun0 ms1.对象不支持此属性或方法Source:  http://localhost:63342/storeExample/js/store.dom.js:65 
3.localValue (0, 1, 1)Rerun1 mstest local store pass
4.global failure (1, 0, 1)Rerun0 ms1.类不能支持 Automation 操作Source:  http://localhost:63342/storeExample/js/store.overflow.js:27 "

The test html code is as below:

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
        "http://www.w3.org/TR/html4/loose.dtd">
<html>

<head>
    <link rel="stylesheet" href="libs/qunit/qunit.css" media="screen">
    <script src="libs/qunit/qunit.js"></script>
    <script type="text/javascript" src="js/store2.js"/>
    <script type="text/javascript" src="js/libs/jquery/jquery.js"/>
    <script src="js/store.bind.js"></script>
    <script src="js/store.cache.js"></script>
    <script src="js/store.old.js"></script>
    <script src="js/store.overflow.js"></script>
    <script src="js/store.quota.js"></script>
    <script src="js/store.measure.js"></script>
    <script src="js/store.array.js"></script>
    <script src="js/store.dot.js"></script>
    <script src="js/store.deep.js"></script>
    <script src="js/store.quota.js"></script>
    <script src="js/store.dom.js"></script>
  
    <title>test store</title>
    <script type="text/javascript">
         function test() {
//             console.log(store.session);
//            store.set("localKey","localValue");
//             alert(store2);
             testLocalStore();
             testSession();
             testNamespaceLocal();
             testNamespaceSession();

        }
        function testLocalStore() {
            store.local("localKey","localValue");
            QUnit.test("localValue",function (assert) {
                assert.equal(store.get("localKey"),"localValue","test local store pass");
            });
        }
       function testSession() {
            store.session("sessionKey","sessionValue");
           //console.log(JSON.stringify(store));
           QUnit.test("store.session",function (assert) {
               assert.equal(store.session.get("sessionKey"),"sessionValue","test session value pass");
//               assert.equal(store('cart.total') ,23.25);
           })
        }
         function testNamespaceSession() {
             var apple = store.namespace('com.sw.mft',false);
             apple.session("nssessionKey","nssessionValue");
//             console.log(apple.toString());
//             console.log(apple.getAll().toString());
            // console.log(store["apple"]);
             QUnit.test("store.testNamespaceSession",function (assert) {
                 assert.equal(store["com.sw.mft"].session.get("nssessionKey"),"nssessionValue","test session value pass");
//               assert.equal(store('cart.total') ,23.25);
             })
         }
        function  testNamespaceLocal() {
            var cart = store.namespace('cart');
            cart('total', 23.25);
            cart('group', 'toys');
            QUnit.test("namespace",function (assert) {
                assert.equal(store.cart.get("group"),"toys","test namespace local value pass");
                assert.equal(store('cart.total') ,23.25);
            })
        }
        test();
    </script>

</head>
<body>
<div id="qunit"></div>
<div id="qunit-fixture"></div>
</body>

</html>

**Comment by nbubna** [comment]
What error are you getting? IE8 does support localStorage (in IE8 mode), so it should work fine.

**Comment by nbubna** [comment]
Also, i can't help but notice that you are using all the plugins, including the alpha quality ones. Why? Your test code doesn't using any of those features. While the core library has been tested in IE8 in the past, most of those plugins never have.

**Comment by 22996963** [comment]
I got it, thanks very much!!!
