### ISSUE TITLE
Typings are missing.

### ISSUE THREAD

**Issue by AndiRudi** [nbubna/store#44]
Hi, I just found out that there are no typings for the project. It would be nice if you can add them. (https://github.com/DefinitelyTyped/DefinitelyTyped)

**Comment by nbubna** [comment]
Yeah, it's not something i've done before. Someone started, but made a few mistakes and never finished. See PR #42

**Comment by nbubna** [comment]
I did some reading on TypeScript and updated it with what i hope is a more accurate and complete version. Please pull the latest version (2.5.3) and tell me if it works for you. Thanks!
