### ISSUE TITLE
cant able to import store2 version 2.5.5 in *.ts file in angular 2

### ISSUE THREAD

**Issue by sp40684** [nbubna/store#47]
Installed npm store2 2.5.5  version in my angular 2 solution.
using the command npm install store2

When i tired to import the store2 in required *.ts file as below
import * as store from 'store2';
Getting error as 
"node_modules/store2/store.d.ts' is not a module." when trying to run the solution

Any help will be appreciated.

**Comment by thomschke** [comment]
try previous version v2.5.4, it's running under TS.

**Comment by thomschke** [comment]
`npm install store2@2.5.4 --save-exact` or `yarn add store2@2.5.4`

**Comment by sp40684** [comment]
Can i know the explicit and versatile functions available in 2.5.4

Earlier used store2 V2.3.0 for my solution. Getting following errors

Property 'remove' does not exist on type 'typeof store'
Property 'each' does not exist on type 'typeof store'
Property 'get' does not exist on type 'typeof store'
Property 'set' does not exist on type 'typeof store'

used this function with reference to V2.3.0.

**Comment by thomschke** [comment]
[https://github.com/nbubna/store/blob/2.5.4/index.d.ts](url)

**Comment by nbubna** [comment]
Ok, i reverted the misguided 2.5.5 changes. 2.5.6 is the new 2.5.4 now. Sorry about that! I'm still learning this TypeScript support stuff.

P.S. If anyone wants to help out. I love tests, but i don't know how to write a test for the typings file, and i'm fairly limited in my time to spend on this project.

**Comment by kevupton** [comment]
@nbubna Just made a PR to fix the typescript problems.

**Comment by nbubna** [comment]
ended up testing this myself and found i need to export the functions and consts in the store namespace so that things like ```store.get('foo', 'alt')``` would register correctly.

Thanks again for the help!
