### ISSUE TITLE
get() returns undefined when should retrieve 0

### ISSUE THREAD

**Issue by AlvaDamian** [nbubna/store#48]
Set a key with value 0:

```javascript
store.set('key', 0);
```
try to get the value:

```javascript
store.get('key');
```

Returns 'undefined'. Works fine when value is not 0

**Comment by AlvaDamian** [comment]
Ignore this. The error was in my code.

I was trying to wrap the get function like this:

```javascript
function get(key, defaultValue) {

  var data = store(key);
  return data ? data : defaultValue;
}
```

Since the value of $data was 0, that condition evaluates to false and $defaultValue was returned. $defaultValue was not defined when calling the function:

```javascript
wrapStorage.get('key');
```

**Comment by nbubna** [comment]
Glad it wasn't a problem. FYI, the default get() function already supports a defaultValue argument. :)
