### ISSUE TITLE
some error in stringify function

### ISSUE THREAD

**Issue by caohanghust** [nbubna/store#50]
var _ = {
        stringify: function(d) {
            return d === undefined || typeof d === "function" ? d+'' : JSON.stringify(d);
        }
}
if typeof d === 'string', d will be stringifyed again
for example, store.local.set(key, value) // key = 'test', value = '{test: 1}'
then value in localstorage will be "{\"test\":1}"

**Comment by nbubna** [comment]
I'm not sure i understand the error you are seeing. Can you give me a test case or a quick *runnable* example so i can see your error?

As far as i can tell, ```store.local.set('test', '{test: 1}')``` works just fine. The value in localStorage will be requoted, but it needs to be in order for JSON.parse to return the same input that went into it (```'{test: 1}'```).

I don't see any errors when i pass in string values. :(

**Comment by nbubna** [comment]
Sorry, without further feedback, i have to consider this bug incorrect/invalid.
