### ISSUE TITLE
make default value configurable

### ISSUE THREAD

**Issue by a-x-** [nbubna/store#52]
At least [`getAll`] and [`keys`] have internal `_and` argument of [`each`] method

[`each`]: https://github.com/nbubna/store/blob/master/src/store2.js#L108 
[`keys`]: https://github.com/nbubna/store/blob/master/src/store2.js#L120
[`getAll`]: https://github.com/nbubna/store/blob/master/src/store2.js#L127

I currently call `getAll()` on empty localStorage and I want to get some exception/rejection or null because I cannot check {} without ugly workarounds and extra libraries

I can propose PR with followed API backward-compatible updates:
- `getAll(default = [])`
- `keys(default = [])`
- rename `_and` to `default`

**Comment by a-x-** [comment]
with default value I can use null or something more advanced like Object('nothing') because null suxx but maybe monad is cool

**Comment by nbubna** [comment]
I like the idea but not the PR. ```_and``` isn't "nothing", but is a way to provide a value for the sequential function calls to access and fill, and to be returned at the end. Frankly, i don't remember why i called it "_and", but i won't be calling it "nothing".

So i won't take the PR as-is, but i will take your idea and add support for ```keys(pushIntoThisList)``` and ```getAll(addToThisObject)```, along with some tests, and documentation.

**Comment by nbubna** [comment]
Do you really need/want it to be able to accept ```null```? I'm finding the idea unpalatable, because if there actually are any keys/values in the store, then both ```keys(null)``` and ```getAll(null)``` will break.

**Comment by nbubna** [comment]
I also wonder why you don't just call store.size() if you are checking whether localStorage is empty.

**Comment by nbubna** [comment]
2.6.0 supports custom fillList and fillObj params to keys and getAll, respectively. They will not work with ```null```, as i can't see any reason to support that. Custom ```Object('nothing')``` will work for getAll, though, so you should be able to achieve your goal easily. Reopen if i'm wrong. :)

**Comment by a-x-** [comment]
Thank you, your points are make sense
