### ISSUE TITLE
How to achieve similar features like Object.assign?

### ISSUE THREAD

**Issue by iamziyue** [nbubna/store#56]
First: `store(key,{id:1,name:'John'})`
I get: `{"id":1,"name":"John"}`
Then: `store(key,{age:40})`
I get: `{"age":40}`
How can I expect to get: `{"id":1,"name":"John","age":40}`
Thanks!

(I translated these into English with Tencent Mr. Translator :))

**Comment by nbubna** [comment]
You'll have to use ```Object.assign```. We don't currently have any sort of ```store.combine(key, newVal)``` function, though that's not a half-bad idea...

First: ```store(key,{id:1,name:'John'})```
Then: ```store.set(key, Object.assign(store.get(key), {age:40}))```

**Comment by nbubna** [comment]
Seeing as such uses have been desired before, i decided to see how hard it'd be to implement a reasonable ```store.add(key, data)``` that would concat to an array, merge two objects, or ```+``` any other combination of types. Turns out it wasn't hard. Version 2.7.0 was just released with this feature. Enjoy!
