### ISSUE TITLE
How to achieve permanent storage on NodeJS?

### ISSUE THREAD

**Issue by jesobreira** [nbubna/store#58]
Once we restart a NodeJS application using store2, it loses all the stored values.

How can we have permanent storage on NodeJS with this lib?

Should this be on the docs?

**Comment by nbubna** [comment]
On NodeJS, eh? Are you using this with JSDOM to provide a backing localStorage implementation? Or just using it directly?

In any case, you would need to have something that is writing the contents to disk, either direct to the filesystem or via a database of sorts. The easiest way would be to plug in something that implements https://developer.mozilla.org/en-US/docs/Web/API/Storage using ```store.area('fs', StorageImplForFS);``` or just expose your persistent Storage implementation as ```localStorage``` on the global, so store2 automatically uses it.

It probably won't be terribly hard to write this to a simple file, but making your implementation synchronous might be tricky. The implementation would probably have to read on init and keep it all in memory to do synchronous "get" ops, and for "set/delete" ops, it'd have to return after doing it in memory and kick off a process.nextTick function to handle synchronizing the file with the in memory version. Or if NodeJS has some way to watch for shut down (i have no idea), write it all to disk then.

Sounds like a fun project, probably not too hard. I don't have time this month, but if you don't beat me too it, i might try it later.

In the meantime, if you're not up for it, i'm sure you can find some persistent key-value storage lib for NodeJS out there. store2 was designed for the browser first and foremost, so it's just not something i've bothered with yet.

**Comment by jesobreira** [comment]
Well, I created this issue because I thought there was already some work done towards it. If you don't mind, I take the task 😄

**Comment by nbubna** [comment]
Your contributions would be most welcome!

**Comment by jesobreira** [comment]
So, I ended up using [node-localstorage](https://www.npmjs.com/package/node-localstorage) which implements the localStorage specs and seemingly worked pretty well.

libs/store.js
```javascript
const store = require('store2')
const localStorage = require('node-localstorage').LocalStorage

module.exports = store.area('fs', localStorage("./some/folder/to/save/data"))
```

test.js
```javascript
var store = require('./libs/store')
let foo = store.namespace('foo')
foo('aaaa', 'ab12')
console.log(foo('aaaa')) // 'ab12' (even if we comment the previous line and run the script again)
```

So far it worked well...

**Comment by nbubna** [comment]
Awesome!! I hadn't noticed that project before. This is something i might even use myself. Thanks for sharing.

Would it work to do something like this:

```javascript
const nodeLocalStorage = require('node-localstorage').LocalStorage
const localStorage = nodeLocalStorage("./some/folder/to/save/data")
const store = require('store2')

module.exports = store;
```

Just curious if it does pick up the `localStorage` reference.
