### ISSUE TITLE
 Cannot read property 'define' of undefined

### ISSUE THREAD

**Issue by liujiefengfeng** [nbubna/store#60]
![image](https://user-images.githubusercontent.com/7887615/39037669-75f43c68-4481-11e8-9341-4687deda222a.png)

**Comment by nbubna** [comment]
Ok... so something, maybe webpack is loading store2 in a context where "this" is undefined...

Do you have any way for me to replicate this so i can learn more? I can change store2 to guard against an undefined 'this', but i would much rather understand what is happening and why.

**Comment by div-production** [comment]
This error appears only when Babel is enabled

**Comment by DanielRuf** [comment]
This issue also appears if the file is directly used in a browser.

This is because `this` points to something else, not `window`.
