### ISSUE TITLE
persistent local storage for different namespaces?

### ISSUE THREAD

**Issue by liujinliang01** [nbubna/store#62]
Hi, 
First of all, I would like to express my heart-felt congratiude for your creation of such a brilliant tool!
I am having a problem and would like some help.
I am trying to store two different categories of things data: 
1. a list of passages, with the title of the passage as key, and the text body as value
2. a list of sentences, keyword as key, sentences as value
I would like the two stores to be persistent so that the next time a user launches the browser, the passages and the sentences are still there, and can be retrieved.
I tried to use:
     var passage_store = new store.namespace('passages')
     var sentence_store = new store.namespace('sentences')
But they are not persistent because, I guess, each time the browser launches, a new instance of store is created which is not the same as the previous launch of the browser.

As long as I can keep the stores separate and persitent, whatever technique, be it namespace or whatever, is alright.

Any help is greatly appreciated，and thank you in advance.
best regards
Jim

**Comment by nbubna** [comment]
Looks like a bug. It's supposed to store just fine. I went and tested and namespaces weren't persisting for me either, and passage_store.isFake() returned true. Blech. I'll try to fix this soon.

**Comment by nbubna** [comment]
Ugh... so overworked right now. I foolishly copied/pasted your code w/o a careful look.

Don't use ```new```. store.namespace is a method, not a constructor!

**Comment by liujinliang01** [comment]
Thanks a million! It really works now.
best regards
Jim
