### ISSUE TITLE
window.store is undefined

### ISSUE THREAD

**Issue by DanielRuf** [nbubna/store#64]
When we use the file directly in a browser context using Gulp which adds the needed wrappers `})(this, this && this.define);` fails as `this` is not `window`. At least `window.store` fails as `window` will be undefined.

https://github.com/nbubna/store/blob/master/dist/store2.js#L254

`})(window, this && this.define);` as workaround solves this.

**Comment by nbubna** [comment]
Yeah, it used to be like this. If i make this change, then doing require('store2') in node will break.

I don't understand what Gulp is doing, why is it changing the 'this' for some "needed wrappers"? What are the needed wrappers? Why are they needed? What is "this" becoming? And do you need to be able to access window.store?

What we want here is ```globalThis```, but i'm not sure that's something to build on yet.

**Comment by janat08** [comment]
breaks on parceljs too.

**Comment by nbubna** [comment]
I won't have time to put much into my OSS JS libs for a while. Can one of y'all make me a simple example i can test with? Even better if it comes with a fix that passes current tests. :)

**Comment by aMarCruz** [comment]
@nbubna ,
rollup is replacing `this` with `undefined`:

![image](https://user-images.githubusercontent.com/6636980/92186733-4c501380-ee1d-11ea-8a5c-a2b6bf8ec86e.png)

From [Rollup Docs](https://rollupjs.org/guide/en/#error-this-is-undefined):

> In a JavaScript module, this is undefined at the top level (i.e., outside functions). Because of that, Rollup will rewrite any this references to undefined so that the resulting behaviour matches what will happen when modules are natively supported.
>
> There are occasional valid reasons for this to mean something else. If you're getting errors in your bundle, you can use options.context and options.moduleContext to change this behaviour.

I'm not using store2 with ES6 modules yet, but using `this` at top level seems to be fragile in the new environments.

**Comment by nbubna** [comment]
Yeah, it's an old pattern. I haven't had time yet to sit down and figure out how to evolve store2 so it can support ES6 modules. It's tempting to just make a clean break with a new major version and go all in, but that will require some thought.
