### ISSUE TITLE
store.on.js extension not triggering events

### ISSUE THREAD

**Issue by maciej-laskowski** [nbubna/store#65]
Hi! First of all thank you for taking the time to create store, the API seems very well thought out. It looks like a perfect fit for my project (especially since it supports namespacing) but I seem to run into some problems when I try to use `store.on.js` with this simple code:
```
<script src="src/store2.js"></script>
<script src="src/store.on.js"></script>
<script>
	store.on('foo', function(){ console.log('event'); });
</script>
```
I get `TypeError: this._out is not a function at store.on.js:25:21` in console as soon as I open a second tab with the same code. Debugging shows that `this` refers to `window` which seems to be a problem, I tried using an arrow function on line 24 to preserve `this` binding to `store` like this `var listener = (e) => {` unfortunately opening two tabs and runing `store.set('foo', 'bar')` in console does not trigger the event in another tab.

I am not a frontend dev so I might be doing something wrong, would you mind having a look?

**Comment by nbubna** [comment]
I'll try to look at this today. I haven't used store.on.js in a while. Sorry it hasn't kept pace.

**Comment by nbubna** [comment]
I'm unable to replicate the problem. Can you create a failing example on jsfiddle or the like?

**Comment by Katochimoto** [comment]
Hello! Have the same problem.
I think this is due to
`var k = this._out(e.key);// undefined if key is not in the namespace`
> Uncaught TypeError: this._out is not a function

**Comment by nbubna** [comment]
What browser is this happening in? And do you have an example or test i can run? I have not been able to replicate it myself.

**Comment by Katochimoto** [comment]
Chrome 77
1 open 2 tabs with the same link
https://output.jsbin.com/biwezekino
2 open dev tools -> console
3 refresh one tab, in another one you will see 
`Uncaught TypeError: this._out is not a function`

`store.bind.js` looks the same and works correct.

**Comment by nbubna** [comment]
Thank you, now i see the problem!
