### ISSUE TITLE
`remove` has different signature than `get`

### ISSUE THREAD

**Issue by aarondfrancis** [nbubna/store#68]
First of all, thanks for the great library! It's wildly useful.

I was using `get(key, {})` to default to an object, and then I realized that I needed to "pull" the `key`, so I switched to using `remove(key, {})`, but found that `remove` doesn't accept the optional `alt` second argument. 

Is that intentional? It would be quite helpful for me if those signatures were the same. 

Thanks!

**Comment by nbubna** [comment]
Is this about signatures or behavior? Unless you are using TypeScript, you can send the second argument to ```remove``` and it won't hurt or do anything. No need to change the signatures just to be able to send a 2nd arg. You can do that already.

If this is about the behavior and you are hoping to have ```remove(key, alt)``` return the alt value when there is no value for the key in the db, that's an interesting idea. Though, i'm not sure what the use case would be. Do you have one?

And of course, you could always implement it as an extension, whether or not it becomes an official feature:
```
store._.fn('unset', function(key, alt) {
  return this.has(key) ? this.remove(key) : alt;
});
```

**Comment by aarondfrancis** [comment]
> If this is about the behavior and you are hoping to have remove(key, alt) return the alt value when there is no value for the key in the db, that's an interesting idea. Though, i'm not sure what the use case would be. Do you have one?

Yeah I guess it's more clear to say the *behavior* doesn't match. Good point.

My use case is I'm working on an internal spreadsheet tool, and every time a cell changes I put the data to the server. Should it fail, I shuttle it off into local storage and wait a certain number of seconds or piggy back on the next request. 

I never know if there are going to be any waiting to hitch a ride, so I need to provide a default. I also need to pull them out of storage, because I don't want to apply them twice.

Here's where I've ended up, with a little helper: 

```js
pullFailedChanges() {
    const failures = store.get('network-failures', {});

    // https://github.com/nbubna/store/issues/68
    store.remove('network-failures');

    return failures;
},
```

I didn't think about writing my own `pull` or `unset` extension, that's a great idea. 

Thanks for your quick response!

**Comment by nbubna** [comment]
It was trivial to add support for ```remove(key, alt)```. It's in v2.9.0
