### ISSUE TITLE
How to import store.on in Node?

### ISSUE THREAD

**Issue by pre-vail** [nbubna/store#72]
I know a similar question was posted a few years ago but I’m not sure that the OP was referring to importing in Node.js. How should that be done for store.on? Can someone post a simple example? I’m getting an error saying that the ‘on’ method does not exist. Thank you.

**Comment by nbubna** [comment]
It's just a JavaScript file at node_modules/store2/src/store.on.js, import it like you would any other file.

That said, before you bother, you'd best make sure that whatever is backing store in your Node setup actually bothers to fire storage events on whatever is serving as the global "window" object. Node is not a browser environment and does not come with window, localStorage, and sessionStorage objects. I believe their are localStorage polyfills, but i don't know that they make it so the window.addEventListener("storage", ...) calls in store.on.js would work, much less ever receive any events.
