### ISSUE TITLE
When Specified key value is null and defaultValue is falsy, the get('nullValue', defaultValue) always return null

### ISSUE THREAD

**Issue by betgar** [nbubna/store#74]
I don't know is this a bug or just `store` designed for this
```javascript
const defaultValue = false // 0, '', 
store.get('nullValue') // value is null
store.get('nullValue', 0) // value is null, expect is 0
```

Is there have some rules about the value type?  must be a object value ?

**Comment by nbubna** [comment]
Not intended, no. That's a bug. Surprised no one has hit that yet...
