### ISSUE TITLE
get() method does not return empty string as alt value

### ISSUE THREAD

**Issue by OsoianMarcel** [nbubna/store#75]
`get()` method does not return empty string as alternative value

To reproduce:
```js
const expectedVal = '';
const actualVal = store2.get('inexistent_key', '');
console.log({
	expectedVal,
	actualVal,
	isOk: expectedVal === actualVal
});
```

P.S. Great library, Thank you.

**Comment by nbubna** [comment]
Have you tried 2.11.1? This looks like a duplicate of #74, fixed 4 days ago. :)

**Comment by OsoianMarcel** [comment]
@nbubna my bad :) yes, fixed!
AWESOME LIBRARY!
