### ISSUE TITLE
Bug about the store.get() method

### ISSUE THREAD

**Issue by rainyulei** [nbubna/store#76]
```javascript
import store from 'store2';
 console.log(store.get('city'), typeof store.get('city'), "======263")
//undefined string ======263
```
When I didn't find the city option in localstorage, the output was an undefined string, not a real undefined.

**Comment by nbubna** [comment]
I can't reproduce this. Ultimately, store.get('city') will take its value from localStorage.getItem('city'), which should return "null", not undefined. Are you certain you did not set the value to "undefined" yourself before this? Remember, localStorage is persistent.

Also, there are several places in the tests that confirm an absent key returns null, for instance:
https://github.com/nbubna/store/blob/master/test/store_test.js#L372
