### ISSUE TITLE
Use a more meaningful test key for localStorage

### ISSUE THREAD

**Issue by Narigo** [nbubna/store#78]
Okay, I admint this is probably a pretty esoteric feature request. I was trying to find out what caused this very short blinking in the local storage development tab:

![image](https://user-images.githubusercontent.com/1767865/82719306-99164100-9ca9-11ea-9106-ecaa6b21edf7.png)

I had to take a video from the screen to see that a `"_-bad-_": "wolf"`was added on each refresh of [storybook](https://storybook.js.org/). Looks like they are using your module internally which in turn creates this key/value for a very short amount of time. Googling "bad", "wolf" and "localStorage" did not yield this result and I'm happy I actually found it through GitHub at all.

It would be nice to change the [testKey](https://github.com/nbubna/store/blob/master/src/store2.js#L57-L58) to something like `"__store2_test_key": "ok"` or anything that makes the paranoid dev aware of where to look for this and understand that this is not something nefarious going on... ;)

Thank you for your consideration!

**Comment by nbubna** [comment]
Heh. Yes, given that it's a Doctor Who reference, i'm not surprised Google was unhelpful. I agree, given the rise in usage, something more "professional" and less mysterious is in order. Must admit i'm rather shocked anyone saw this happen in action, rather than just notice it in the source.

Want to do a PR so you can get credit? Totally optional, i'll do it if you don't. Though, i'd personally go with _store2_test_, as "key" seems redundant. :

**Comment by Narigo** [comment]
Here you are: https://github.com/nbubna/store/pull/79
I did not check out / try the code as setting up the environment would take me too long right now. I only stumbled across this while debugging and wanted to understand where it came from...

While looking at the code, could `store._area = _.storage('fake');` go into the catch block? Or might it be set before the test in some cases?

**Comment by nbubna** [comment]
All good. And yeah, that could go in the catch block. I originally wrote this way back when IE7 was still a thing. I was a little paranoid trying to ensure the full set-then-remove path was functional, as the browser world was more fragile there and throw-no-errors was a firm requirement. But it's 2020, and i see no reason to be so paranoid still. :)
